# Generated by Django 2.2.27 on 2022-05-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_task_epsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_type',
            field=models.CharField(blank=True, help_text='A label for the file type', max_length=255, null=True, verbose_name='File Type'),
        ),
    ]
